// This file is auto-generated by @hey-api/openapi-ts

/**
 * Product model
 * Product model
 */
export type Product = {
    /**
     * ID
     * ID
     */
    id?: number;
    /**
     * Name
     * Product name
     */
    name?: string;
    /**
     * Category
     * Product category id
     */
    product_category_id?: number;
    /**
     * Quantity
     * Product quantity
     */
    quantity?: number;
    /**
     * Deleted
     * Is product deleted?
     */
    deleted?: boolean;
    /**
     * Price
     * Product price per piece
     */
    price?: number;
};

/**
 * ProductCategory model
 * ProductCategory model
 */
export type ProductCategory = {
    /**
     * ID
     * ID
     */
    id?: number;
    /**
     * Name
     * Product Category name
     */
    name?: string;
    /**
     * Description
     * Product Category description
     */
    description?: string;
    /**
     * Deleted
     * Is product category deleted?
     */
    deleted?: boolean;
};

/**
 * User model
 * User model
 */
export type User = unknown;

export type GetProductCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Should include deleted product category
         */
        includeDeleted?: boolean;
    };
    url: '/product-categories';
};

export type GetProductCategoriesResponses = {
    /**
     * successful operation
     */
    default: Array<ProductCategory>;
};

export type GetProductCategoriesResponse = GetProductCategoriesResponses[keyof GetProductCategoriesResponses];

export type CreateProductCategoryData = {
    /**
     * Create product category object
     */
    body: ProductCategory;
    path?: never;
    query?: never;
    url: '/product-categories';
};

export type CreateProductCategoryResponses = {
    /**
     * successful operation
     */
    default: unknown;
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Should include deleted product
         */
        includeDeleted?: boolean;
    };
    url: '/products';
};

export type GetProductsResponses = {
    /**
     * successful operation
     */
    default: Array<Product>;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type CreateProductData = {
    /**
     * Create product object
     */
    body: Product;
    path?: never;
    query?: never;
    url: '/products';
};

export type CreateProductResponses = {
    /**
     * successful operation
     */
    default: unknown;
};

export type ShowProductData = {
    body?: never;
    path: {
        /**
         * ID of product to return
         */
        productId: number;
    };
    query?: never;
    url: '/products/{productId}';
};

export type ShowProductErrors = {
    /**
     * Invalid ID supplier
     */
    400: unknown;
    /**
     * Product not found
     */
    404: unknown;
};

export type ShowProductResponses = {
    /**
     * successful operation
     */
    200: Product;
};

export type ShowProductResponse = ShowProductResponses[keyof ShowProductResponses];

export type UpdateProductData = {
    /**
     * Update product object
     */
    body: Product;
    path: {
        /**
         * ID of product to return
         */
        productId: number;
    };
    query?: never;
    url: '/products/{productId}';
};

export type UpdateProductResponses = {
    /**
     * successful operation
     */
    default: unknown;
};

export type ShowUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type ShowUserResponses = {
    /**
     * successful operation
     */
    default: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost/api' | (string & {});
};