// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, name, pin_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, role, name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	Name         string      `json:"name"`
	PinHash      pgtype.Text `json:"pin_hash"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Name,
		arg.PinHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, name, created_at, updated_at, pin_hash
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, name, created_at, updated_at, pin_hash
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinHash,
	)
	return i, err
}

const getUserByPIN = `-- name: GetUserByPIN :one
SELECT id, email, password_hash, role, name, created_at, updated_at, pin_hash
FROM users
WHERE email = $1 AND pin_hash = $2
`

type GetUserByPINParams struct {
	Email   string      `json:"email"`
	PinHash pgtype.Text `json:"pin_hash"`
}

func (q *Queries) GetUserByPIN(ctx context.Context, arg GetUserByPINParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPIN, arg.Email, arg.PinHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinHash,
	)
	return i, err
}

const listCashiers = `-- name: ListCashiers :many
SELECT id, email, role, name, created_at, updated_at, pin_hash
FROM users
WHERE role = 'cashier'
ORDER BY created_at DESC
`

type ListCashiersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	PinHash   pgtype.Text        `json:"pin_hash"`
}

func (q *Queries) ListCashiers(ctx context.Context) ([]ListCashiersRow, error) {
	rows, err := q.db.Query(ctx, listCashiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCashiersRow
	for rows.Next() {
		var i ListCashiersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PinHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPin = `-- name: UpdateUserPin :one
UPDATE users
SET pin_hash = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, role, name, updated_at
`

type UpdateUserPinParams struct {
	ID      pgtype.UUID `json:"id"`
	PinHash pgtype.Text `json:"pin_hash"`
}

type UpdateUserPinRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Name      string             `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPin(ctx context.Context, arg UpdateUserPinParams) (UpdateUserPinRow, error) {
	row := q.db.QueryRow(ctx, updateUserPin, arg.ID, arg.PinHash)
	var i UpdateUserPinRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}
