// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBarcodeExists = `-- name: CheckBarcodeExists :one
SELECT EXISTS(SELECT 1 FROM variants WHERE barcode = $1 AND barcode IS NOT NULL AND ($2::uuid IS NULL OR id != $2)) as exists
`

type CheckBarcodeExistsParams struct {
	Barcode pgtype.Text `json:"barcode"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) CheckBarcodeExists(ctx context.Context, arg CheckBarcodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBarcodeExists, arg.Barcode, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSKUExists = `-- name: CheckSKUExists :one
SELECT EXISTS(SELECT 1 FROM variants WHERE sku = $1 AND ($2::uuid IS NULL OR id != $2)) as exists
`

type CheckSKUExistsParams struct {
	Sku     string      `json:"sku"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) CheckSKUExists(ctx context.Context, arg CheckSKUExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSKUExists, arg.Sku, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, description, parent_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, parent_id, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Description, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, category_id, image_url, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, category_id, image_url, is_active, created_at, updated_at
`

type CreateProductParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CategoryID  pgtype.UUID `json:"category_id"`
	ImageUrl    pgtype.Text `json:"image_url"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO variants (product_id, sku, barcode, name, price, cost, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, sku, barcode, name, price, cost, is_active, created_at, updated_at
`

type CreateVariantParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Sku       string      `json:"sku"`
	Barcode   pgtype.Text `json:"barcode"`
	Name      string      `json:"name"`
	Price     int64       `json:"price"`
	Cost      pgtype.Int8 `json:"cost"`
	IsActive  pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.Name,
		arg.Price,
		arg.Cost,
		arg.IsActive,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, description, parent_id, created_at, updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, category_id, image_url, is_active, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductWithCategory = `-- name: GetProductWithCategory :one
SELECT p.id, p.name, p.description, p.category_id, p.image_url, p.is_active, p.created_at, p.updated_at,
       c.id as category_id, c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.id = $1
`

type GetProductWithCategoryRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryID_2 pgtype.UUID        `json:"category_id_2"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetProductWithCategory(ctx context.Context, id pgtype.UUID) (GetProductWithCategoryRow, error) {
	row := q.db.QueryRow(ctx, getProductWithCategory, id)
	var i GetProductWithCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID_2,
		&i.CategoryName,
	)
	return i, err
}

const getProductWithVariants = `-- name: GetProductWithVariants :one
SELECT p.id, p.name, p.description, p.category_id, p.image_url, p.is_active, p.created_at, p.updated_at,
       c.id as category_id, c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.id = $1
`

type GetProductWithVariantsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryID_2 pgtype.UUID        `json:"category_id_2"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetProductWithVariants(ctx context.Context, id pgtype.UUID) (GetProductWithVariantsRow, error) {
	row := q.db.QueryRow(ctx, getProductWithVariants, id)
	var i GetProductWithVariantsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID_2,
		&i.CategoryName,
	)
	return i, err
}

const getVariant = `-- name: GetVariant :one
SELECT id, product_id, sku, barcode, name, price, cost, is_active, created_at, updated_at
FROM variants
WHERE id = $1
`

func (q *Queries) GetVariant(ctx context.Context, id pgtype.UUID) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariant, id)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByBarcode = `-- name: GetVariantByBarcode :one
SELECT id, product_id, sku, barcode, name, price, cost, is_active, created_at, updated_at
FROM variants
WHERE barcode = $1
`

func (q *Queries) GetVariantByBarcode(ctx context.Context, barcode pgtype.Text) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantByBarcode, barcode)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantBySKU = `-- name: GetVariantBySKU :one
SELECT id, product_id, sku, barcode, name, price, cost, is_active, created_at, updated_at
FROM variants
WHERE sku = $1
`

func (q *Queries) GetVariantBySKU(ctx context.Context, sku string) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantBySKU, sku)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, parent_id, created_at, updated_at
FROM categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.name, p.description, p.category_id, p.image_url, p.is_active, p.created_at, p.updated_at
FROM products p
WHERE ($1::uuid IS NULL OR p.category_id = $1)
  AND ($2::boolean IS NULL OR p.is_active = $2)
ORDER BY p.name
`

type ListProductsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 bool        `json:"column_2"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, name, description, category_id, image_url, is_active, created_at, updated_at
FROM products
WHERE category_id = $1
ORDER BY name
`

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, sku, barcode, name, price, cost, is_active, created_at, updated_at
FROM variants
WHERE product_id = $1
ORDER BY name
`

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID pgtype.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variant
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Name,
			&i.Price,
			&i.Cost,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProductID = `-- name: ListVariantsByProductID :many
SELECT id, product_id, sku, barcode, name, price, cost, is_active, created_at, updated_at
FROM variants
WHERE product_id = $1
ORDER BY name
`

func (q *Queries) ListVariantsByProductID(ctx context.Context, productID pgtype.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variant
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Name,
			&i.Price,
			&i.Cost,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVariant = `-- name: SearchVariant :one
SELECT v.id, v.product_id, v.sku, v.barcode, v.name, v.price, v.cost, v.is_active, v.created_at, v.updated_at,
       p.name as product_name
FROM variants v
JOIN products p ON v.product_id = p.id
WHERE v.barcode = $1 OR v.sku = $1
`

type SearchVariantRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	Sku         string             `json:"sku"`
	Barcode     pgtype.Text        `json:"barcode"`
	Name        string             `json:"name"`
	Price       int64              `json:"price"`
	Cost        pgtype.Int8        `json:"cost"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProductName string             `json:"product_name"`
}

func (q *Queries) SearchVariant(ctx context.Context, barcode pgtype.Text) (SearchVariantRow, error) {
	row := q.db.QueryRow(ctx, searchVariant, barcode)
	var i SearchVariantRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductName,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, description = $3, parent_id = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, parent_id, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, description = $3, category_id = $4, image_url = $5, is_active = $6, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, category_id, image_url, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CategoryID  pgtype.UUID `json:"category_id"`
	ImageUrl    pgtype.Text `json:"image_url"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE variants
SET sku = $2, barcode = $3, name = $4, price = $5, cost = $6, is_active = $7, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, product_id, sku, barcode, name, price, cost, is_active, created_at, updated_at
`

type UpdateVariantParams struct {
	ID       pgtype.UUID `json:"id"`
	Sku      string      `json:"sku"`
	Barcode  pgtype.Text `json:"barcode"`
	Name     string      `json:"name"`
	Price    int64       `json:"price"`
	Cost     pgtype.Int8 `json:"cost"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ID,
		arg.Sku,
		arg.Barcode,
		arg.Name,
		arg.Price,
		arg.Cost,
		arg.IsActive,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
