// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO inventory_ledger (variant_id, quantity_change, reason, reference_id, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, variant_id, quantity_change, reason, reference_id, created_at, created_by
`

type CreateLedgerEntryParams struct {
	VariantID      pgtype.UUID `json:"variant_id"`
	QuantityChange int64       `json:"quantity_change"`
	Reason         string      `json:"reason"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (InventoryLedger, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.VariantID,
		arg.QuantityChange,
		arg.Reason,
		arg.ReferenceID,
		arg.CreatedBy,
	)
	var i InventoryLedger
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.QuantityChange,
		&i.Reason,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLedgerEntry = `-- name: GetLedgerEntry :one
SELECT id, variant_id, quantity_change, reason, reference_id, created_at, created_by
FROM inventory_ledger
WHERE id = $1
`

func (q *Queries) GetLedgerEntry(ctx context.Context, id pgtype.UUID) (InventoryLedger, error) {
	row := q.db.QueryRow(ctx, getLedgerEntry, id)
	var i InventoryLedger
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.QuantityChange,
		&i.Reason,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getStockLevel = `-- name: GetStockLevel :one
SELECT COALESCE(SUM(quantity_change), 0)::BIGINT as stock_level
FROM inventory_ledger
WHERE variant_id = $1
`

func (q *Queries) GetStockLevel(ctx context.Context, variantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getStockLevel, variantID)
	var stock_level int64
	err := row.Scan(&stock_level)
	return stock_level, err
}

const getStockLevelByVariants = `-- name: GetStockLevelByVariants :many
SELECT requested.variant_id::uuid AS variant_id, COALESCE(SUM(ledger.quantity_change), 0)::BIGINT as stock_level
FROM unnest($1::uuid[]) AS requested(variant_id)
LEFT JOIN inventory_ledger AS ledger ON ledger.variant_id = requested.variant_id
GROUP BY requested.variant_id
`

type GetStockLevelByVariantsRow struct {
	VariantID  pgtype.UUID `json:"variant_id"`
	StockLevel int64       `json:"stock_level"`
}

func (q *Queries) GetStockLevelByVariants(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetStockLevelByVariantsRow, error) {
	rows, err := q.db.Query(ctx, getStockLevelByVariants, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStockLevelByVariantsRow
	for rows.Next() {
		var i GetStockLevelByVariantsRow
		if err := rows.Scan(&i.VariantID, &i.StockLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, variant_id, quantity_change, reason, reference_id, created_at, created_by
FROM inventory_ledger
WHERE variant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesParams struct {
	VariantID pgtype.UUID `json:"variant_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]InventoryLedger, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries, arg.VariantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryLedger
	for rows.Next() {
		var i InventoryLedger
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.QuantityChange,
			&i.Reason,
			&i.ReferenceID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
