// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SortOrder   int64              `json:"sort_order"`
}

type GrossProfitReport struct {
	Month           string `json:"month"`
	OrderCount      int64  `json:"order_count"`
	Revenue         int64  `json:"revenue"`
	CostOfGoodsSold int64  `json:"cost_of_goods_sold"`
	GrossProfit     int64  `json:"gross_profit"`
}

type InventoryLedger struct {
	ID             pgtype.UUID        `json:"id"`
	VariantID      pgtype.UUID        `json:"variant_id"`
	QuantityChange int64              `json:"quantity_change"`
	Reason         string             `json:"reason"`
	ReferenceID    pgtype.UUID        `json:"reference_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

type MonthlySalesReport struct {
	Month             string `json:"month"`
	OrderCount        int64  `json:"order_count"`
	TotalRevenue      int64  `json:"total_revenue"`
	AverageOrderValue int64  `json:"average_order_value"`
}

type Order struct {
	ID             pgtype.UUID        `json:"id"`
	ClientUuid     string             `json:"client_uuid"`
	UserID         pgtype.UUID        `json:"user_id"`
	Status         string             `json:"status"`
	TotalAmount    int64              `json:"total_amount"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DiscountAmount int64              `json:"discount_amount"`
}

type OrderItem struct {
	ID         pgtype.UUID        `json:"id"`
	OrderID    pgtype.UUID        `json:"order_id"`
	VariantID  pgtype.UUID        `json:"variant_id"`
	Quantity   int32              `json:"quantity"`
	UnitPrice  int64              `json:"unit_price"`
	Subtotal   int64              `json:"subtotal"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CostAtSale pgtype.Int8        `json:"cost_at_sale"`
}

type Payment struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	Method         string             `json:"method"`
	TenderedAmount int64              `json:"tendered_amount"`
	ChangeDue      int64              `json:"change_due"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PinHash      pgtype.Text        `json:"pin_hash"`
}

type Variant struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Sku       string             `json:"sku"`
	Barcode   pgtype.Text        `json:"barcode"`
	Name      string             `json:"name"`
	Price     int64              `json:"price"`
	Cost      pgtype.Int8        `json:"cost"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
