// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package sqlc

import (
	"context"
)

const listGrossProfit = `-- name: ListGrossProfit :many
SELECT month, order_count, revenue, cost_of_goods_sold, gross_profit
FROM gross_profit_report
ORDER BY month DESC
`

// gross-profit read model
func (q *Queries) ListGrossProfit(ctx context.Context) ([]GrossProfitReport, error) {
	rows, err := q.db.Query(ctx, listGrossProfit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrossProfitReport
	for rows.Next() {
		var i GrossProfitReport
		if err := rows.Scan(
			&i.Month,
			&i.OrderCount,
			&i.Revenue,
			&i.CostOfGoodsSold,
			&i.GrossProfit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlySales = `-- name: ListMonthlySales :many
SELECT month, order_count, total_revenue, average_order_value
FROM monthly_sales_report
ORDER BY month DESC
`

// monthly-sales read model
func (q *Queries) ListMonthlySales(ctx context.Context) ([]MonthlySalesReport, error) {
	rows, err := q.db.Query(ctx, listMonthlySales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlySalesReport
	for rows.Next() {
		var i MonthlySalesReport
		if err := rows.Scan(
			&i.Month,
			&i.OrderCount,
			&i.TotalRevenue,
			&i.AverageOrderValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
