// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (client_uuid, user_id, status, total_amount)
VALUES ($1, $2, $3, $4)
ON CONFLICT (client_uuid) DO NOTHING
RETURNING id, client_uuid, user_id, status, total_amount, created_at, updated_at
`

type CreateOrderParams struct {
	ClientUuid  string      `json:"client_uuid"`
	UserID      pgtype.UUID `json:"user_id"`
	Status      string      `json:"status"`
	TotalAmount int64       `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ClientUuid,
		arg.UserID,
		arg.Status,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, variant_id, quantity, unit_price, subtotal, cost_at_sale)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, variant_id, quantity, unit_price, subtotal, cost_at_sale, created_at
`

type CreateOrderItemParams struct {
	OrderID    pgtype.UUID `json:"order_id"`
	VariantID  pgtype.UUID `json:"variant_id"`
	Quantity   int32       `json:"quantity"`
	UnitPrice  int64       `json:"unit_price"`
	Subtotal   int64       `json:"subtotal"`
	CostAtSale pgtype.Int8 `json:"cost_at_sale"`
}

type CreateOrderItemRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrderID    pgtype.UUID        `json:"order_id"`
	VariantID  pgtype.UUID        `json:"variant_id"`
	Quantity   int32              `json:"quantity"`
	UnitPrice  int64              `json:"unit_price"`
	Subtotal   int64              `json:"subtotal"`
	CostAtSale pgtype.Int8        `json:"cost_at_sale"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (CreateOrderItemRow, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.Quantity,
		arg.UnitPrice,
		arg.Subtotal,
		arg.CostAtSale,
	)
	var i CreateOrderItemRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.CostAtSale,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, method, tendered_amount, change_due, paid_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, order_id, method, tendered_amount, change_due, paid_at, created_at
`

type CreatePaymentParams struct {
	OrderID        pgtype.UUID `json:"order_id"`
	Method         string      `json:"method"`
	TenderedAmount int64       `json:"tendered_amount"`
	ChangeDue      int64       `json:"change_due"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Method,
		arg.TenderedAmount,
		arg.ChangeDue,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.TenderedAmount,
		&i.ChangeDue,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByClientUUID = `-- name: GetOrderByClientUUID :one
SELECT id, client_uuid, user_id, status, total_amount, created_at, updated_at
FROM orders
WHERE client_uuid = $1
`

func (q *Queries) GetOrderByClientUUID(ctx context.Context, clientUuid string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByClientUUID, clientUuid)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, client_uuid, user_id, status, total_amount, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, method, tendered_amount, change_due, paid_at, created_at
FROM payments
WHERE order_id = $1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.TenderedAmount,
		&i.ChangeDue,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, variant_id, quantity, unit_price, subtotal, cost_at_sale, created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

type ListOrderItemsByOrderIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrderID    pgtype.UUID        `json:"order_id"`
	VariantID  pgtype.UUID        `json:"variant_id"`
	Quantity   int32              `json:"quantity"`
	UnitPrice  int64              `json:"unit_price"`
	Subtotal   int64              `json:"subtotal"`
	CostAtSale pgtype.Int8        `json:"cost_at_sale"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]ListOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsByOrderIDRow
	for rows.Next() {
		var i ListOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.CostAtSale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, client_uuid, user_id, status, total_amount, created_at, updated_at
FROM orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientUuid,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
