/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosRouteRouteImport } from './routes/pos/route'
import { Route as ErpRouteRouteImport } from './routes/erp/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as InventoryAdjustmentRouteImport } from './routes/inventory/adjustment'
import { Route as ErpInventoryRouteRouteImport } from './routes/erp/inventory/route'

const PosRouteRoute = PosRouteRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpRouteRoute = ErpRouteRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRouteRoute,
} as any)
const InventoryAdjustmentRoute = InventoryAdjustmentRouteImport.update({
  id: '/inventory/adjustment',
  path: '/inventory/adjustment',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpInventoryRouteRoute = ErpInventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ErpRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/erp': typeof ErpRouteRouteWithChildren
  '/pos': typeof PosRouteRouteWithChildren
  '/erp/inventory': typeof ErpInventoryRouteRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/pos/': typeof PosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/erp': typeof ErpRouteRouteWithChildren
  '/erp/inventory': typeof ErpInventoryRouteRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/pos': typeof PosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/erp': typeof ErpRouteRouteWithChildren
  '/pos': typeof PosRouteRouteWithChildren
  '/erp/inventory': typeof ErpInventoryRouteRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/pos/': typeof PosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/erp'
    | '/pos'
    | '/erp/inventory'
    | '/inventory/adjustment'
    | '/pos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/erp' | '/erp/inventory' | '/inventory/adjustment' | '/pos'
  id:
    | '__root__'
    | '/'
    | '/erp'
    | '/pos'
    | '/erp/inventory'
    | '/inventory/adjustment'
    | '/pos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErpRouteRoute: typeof ErpRouteRouteWithChildren
  PosRouteRoute: typeof PosRouteRouteWithChildren
  InventoryAdjustmentRoute: typeof InventoryAdjustmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp': {
      id: '/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof ErpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRouteRoute
    }
    '/inventory/adjustment': {
      id: '/inventory/adjustment'
      path: '/inventory/adjustment'
      fullPath: '/inventory/adjustment'
      preLoaderRoute: typeof InventoryAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp/inventory': {
      id: '/erp/inventory'
      path: '/inventory'
      fullPath: '/erp/inventory'
      preLoaderRoute: typeof ErpInventoryRouteRouteImport
      parentRoute: typeof ErpRouteRoute
    }
  }
}

interface ErpRouteRouteChildren {
  ErpInventoryRouteRoute: typeof ErpInventoryRouteRoute
}

const ErpRouteRouteChildren: ErpRouteRouteChildren = {
  ErpInventoryRouteRoute: ErpInventoryRouteRoute,
}

const ErpRouteRouteWithChildren = ErpRouteRoute._addFileChildren(
  ErpRouteRouteChildren,
)

interface PosRouteRouteChildren {
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteRouteChildren: PosRouteRouteChildren = {
  PosIndexRoute: PosIndexRoute,
}

const PosRouteRouteWithChildren = PosRouteRoute._addFileChildren(
  PosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErpRouteRoute: ErpRouteRouteWithChildren,
  PosRouteRoute: PosRouteRouteWithChildren,
  InventoryAdjustmentRoute: InventoryAdjustmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
