type PosLocale = 'th' | 'en'

const en = {
  sell: 'Sell',
  selling: 'Selling',
  online: 'Online',
  offline: 'Offline',
  tasks: 'Other tasks',
  inventory: 'Adjust stock',
  signOut: 'Sign out',
  searchPlaceholder: 'Search product or scan barcode',
  scanCamera: 'Scan with camera',
  frequent: 'Frequently sold',
  products: 'Products',
  allItems: 'All items',
  allCategories: 'All categories',
  fewerCategories: 'Fewer categories',
  viewOrder: 'View order',
  added: 'Added',
  undo: 'Undo',
  chooseOption: 'Choose an option',
  order: 'Review order',
  clearOrder: 'Clear order',
  clearOrderQuestion: 'Clear this order?',
  keepOrder: 'Keep order',
  itemCount: 'Items',
  subtotal: 'Subtotal',
  addDiscount: 'Add discount',
  discount: 'Discount',
  totalDue: 'Total due',
  continuePayment: 'Continue to payment',
  payment: 'Take payment',
  cash: 'Cash',
  qr: 'QR payment',
  exact: 'Exact',
  amountReceived: 'Amount received',
  changeDue: 'Change due',
  confirmPayment: 'Confirm payment',
  saveOffline: 'Save sale on this phone',
  back: 'Back',
  completing: 'Saving sale…',
  done: 'Sale complete',
  savedOnPhone: 'Saved on this phone',
  savedOnPhoneHelp: 'It will sync automatically when the connection returns.',
  nextSale: 'Start next sale',
  printAgain: 'Print again',
  retry: 'Try again',
  emptyOrder: 'No items yet',
  emptyOrderHelp: 'Choose a product to start this sale.',
  remove: 'Remove',
  decrease: 'Decrease quantity',
  increase: 'Increase quantity',
  paymentError: 'The sale was not saved. Your order is still here. Try again.',
  productLoadError: 'Products could not be loaded.',
  noProducts: 'No products in this category.',
  searchNotFound: 'Product not found. Check the name or barcode.',
  latestReceipt: 'Latest receipt',
  reprintReceipt: 'Print latest receipt',
  close: 'Close',
} as const

const th: Record<keyof typeof en, string> = {
  sell: 'ขายสินค้า',
  selling: 'หน้าขาย',
  online: 'ออนไลน์',
  offline: 'ออฟไลน์',
  tasks: 'งานอื่น',
  inventory: 'ปรับสต็อก',
  signOut: 'ออกจากระบบ',
  searchPlaceholder: 'ค้นหาสินค้า หรือสแกนบาร์โค้ด',
  scanCamera: 'สแกนด้วยกล้อง',
  frequent: 'ขายบ่อย',
  products: 'สินค้า',
  allItems: 'ทั้งหมด',
  allCategories: 'ดูหมวดทั้งหมด',
  fewerCategories: 'ย่อหมวดสินค้า',
  viewOrder: 'ดูรายการ',
  added: 'เพิ่มแล้ว',
  undo: 'ยกเลิก',
  chooseOption: 'เลือกแบบสินค้า',
  order: 'ตรวจรายการ',
  clearOrder: 'ล้างรายการ',
  clearOrderQuestion: 'ต้องการล้างรายการนี้หรือไม่',
  keepOrder: 'เก็บรายการไว้',
  itemCount: 'จำนวน',
  subtotal: 'ยอดรวม',
  addDiscount: 'เพิ่มส่วนลด',
  discount: 'ส่วนลด',
  totalDue: 'ยอดที่ต้องชำระ',
  continuePayment: 'ไปหน้ารับเงิน',
  payment: 'รับชำระเงิน',
  cash: 'เงินสด',
  qr: 'จ่ายด้วย QR',
  exact: 'รับพอดี',
  amountReceived: 'รับเงินมา',
  changeDue: 'เงินทอน',
  confirmPayment: 'ยืนยันรับเงิน',
  saveOffline: 'บันทึกการขายในเครื่องนี้',
  back: 'ย้อนกลับ',
  completing: 'กำลังบันทึก…',
  done: 'ขายสำเร็จ',
  savedOnPhone: 'บันทึกไว้ในเครื่องนี้แล้ว',
  savedOnPhoneHelp: 'ระบบจะส่งข้อมูลให้อัตโนมัติเมื่อกลับมาออนไลน์',
  nextSale: 'เริ่มขายรายการใหม่',
  printAgain: 'พิมพ์อีกครั้ง',
  retry: 'ลองใหม่',
  emptyOrder: 'ยังไม่มีสินค้า',
  emptyOrderHelp: 'เลือกสินค้าเพื่อเริ่มรายการขาย',
  remove: 'ลบ',
  decrease: 'ลดจำนวน',
  increase: 'เพิ่มจำนวน',
  paymentError: 'ยังบันทึกการขายไม่ได้ รายการยังอยู่ครบ กรุณาลองใหม่',
  productLoadError: 'โหลดสินค้าไม่ได้',
  noProducts: 'ไม่มีสินค้าในหมวดนี้',
  searchNotFound: 'ไม่พบสินค้า กรุณาตรวจชื่อหรือบาร์โค้ด',
  latestReceipt: 'ใบเสร็จล่าสุด',
  reprintReceipt: 'พิมพ์ใบเสร็จล่าสุด',
  close: 'ปิด',
}

const configuredLocale = String(import.meta.env.VITE_POS_LOCALE ?? (import.meta.env.MODE === 'test' ? 'en' : 'th')).toLowerCase()
export const posLocale: PosLocale = configuredLocale.startsWith('en') ? 'en' : 'th'
export const posCopy = posLocale === 'th' ? th : en
